cargo-features = [ "edition2021" ]

[package]
name = "luwu-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luwu = { path = "../" }
tracing = "0.1.26"
